const userData = [
  {
    "id":"1",
    "name":"shivam",
    "age":"24",
    "city":"Noida",
    "email":"shivam@gmail.com",
  },
  {
    "id":"2",
    "name":"Bhaskar",
    "age":"26",
    "city":"Dehli",
    "email":"bhaskar@gmail.com",
  },
  {
    "id":"3",
    "name":"Ravi",
    "age":"24",
    "city":"Noida",
    "email":"ravi@gmail.com"
  },
  {
    "id":"4",
    "name":"Ritesh",
    "age":"24",
    "city":"Noida",
    "email":"ritesh@gmail.com"
  },
  {
    "id":"5",
    "name":"Sachin",
    "age":"26",
    "city":"Noida",
    "email":"sachin@gmail.com",
  },
  {
    "id":"6",
    "name":"Ramesh",
    "age":"26",
    "city":"Noida",
    "email":"ramesh@gmail.com",
  },
  {
    "id":"7",
    "name":"Yash",
    "age":"20",
    "city":"bhopal",
    "email":"yash@gmail.com",
  },
  {
    "id":"8",
    "name":"Aman",
    "age":"20",
    "city":"indore",
    "email":"aman@gmail.com"
  },
  {
    "id":"9",
    "name":"Alok",
    "age":"20",
    "city":"Bhopal",
    "email":"alok@gmail.com"
  },
  { 
    "id":"10",
    "name":"Shubham",
    "age":"22",
    "city":"Pune",
    "email":"shubham@gmail.com"
  },
  {
    "id":"11",
    "name":"Karan",
    "age":"22",
    "city":"Raisen",
    "email":"karan@gmail.com"
  },
  {
    "id":"12",
    "name":"Rahul",
    "age":"22",
    "city":"Raisen",
    "email":"rahul@gmail.com"
  },
  {
    "id":"13",
    "name":"Hemant",
    "age":"22",
    "city":"bhopal",
    "email":"hemant@gmail.com"
  },
  {
    "id":"14",
    "name":"Chetan",
    "age":"24",
    "city":"indore",
    "email":"chetan@gmail.com"
  },

];
module.exports = userData;